name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  base-directory:  # id of input
    description: 'Base directory of current repository!'
    required: true
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'