on: [push]

jobs:
  copy_json_content:
    runs-on: ubuntu-latest
    name: A Job to Copy Json contents
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Copy Json Content
        uses: ./ # Uses an action in the root directory
        id: jsonCopy
        with:
          base-directory: ${{github.workspace}}
      # Use the output from the `hello` step
      - name: Copy Json Content Result
        run: echo "${{ steps.jsonCopy.outputs.result }}"

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Updated the destionation json from source value'
          add: '*.json'